### ISSUE TITLE
Hello   UMD | React

### ISSUE THREAD

**Issue by appleearth008** [nedphae/customer-web-client#2]
Hi, see you wonderful code.
I have a quick question:

How do you generate this `index.umd.js` <customer-web-client/chat-server/src/public/chat/component/index.umd.js> file?

Do you have a specific tutorial to follow?

Great thanks!

**Comment by mehcsbegzz** [comment]
cd to react-component-lib 
then run `yarn build`  then you can find index.umd.js in  react-component-lib/dist ,
index.umd.js is a AlimeComponent for [ChatUI](https://chatui.io/sdk/custom-component)

**Comment by mehcsbegzz** [comment]
Sorry for taking so long to reply，many work todo，later i will add  some document to this project
